version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - Jyguy
  labels:
  - dependencies
  versioning-strategy: increase
  ignore: []
