version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - Jyguy
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: mathjs
    versions:
    - 9.0.0
    - 9.1.0
    - 9.2.0
    - 9.3.0
    - 9.3.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: dateformat
    versions:
    - 4.5.0
