CREATE TABLE IF NOT EXISTS biography (email TEXT, summary TEXT, twitter TEXT, userid TEXT, UNIQUE(userid));
CREATE TABLE IF NOT EXISTS blacklist (executor TEXT, guildid TEXT, reason TEXT, userid TEXT, UNIQUE(guildid, userid));
CREATE TABLE IF NOT EXISTS blacklistmsg (bool BOOLEAN, guildid TEXT, UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS cmdnotfound (bool BOOLEAN, guildid TEXT, UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS cooldownmsg (bool BOOLEAN, guildid TEXT, UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS daily (endsat BIGINT, userid TEXT, UNIQUE(userid));
CREATE TABLE IF NOT EXISTS deleteinvite (bool BOOLEAN, guildid TEXT, UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS disabledcommands (command TEXT, guildid TEXT);
CREATE TABLE IF NOT EXISTS economy (balance INTEGER, userid TEXT, UNIQUE(userid));
CREATE TABLE IF NOT EXISTS gblacklist (memberid TEXT, reason TEXT, UNIQUE(memberid));
CREATE TABLE IF NOT EXISTS guildtag (guildid TEXT, tagcontent TEXT, tagname TEXT, UNIQUE(guildid, tagname));
CREATE TABLE IF NOT EXISTS goodbyemsg (guildid TEXT, msg TEXT, UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS levelblock (bool BOOLEAN, channelid TEXT, UNIQUE(channelid));
CREATE TABLE IF NOT EXISTS levelmodifier (guildid TEXT, modifier SMALLINT, UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS levelmsg (bool BOOLEAN, guildid TEXT, UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS levelrole (guildid TEXT, lvl INTEGER, roleid TEXT, UNIQUE(roleid), UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS logchannel (channelid TEXT, guildid TEXT, UNIQUE(channelid), UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS logwebhook (channelid TEXT, guildid TEXT, webhookid TEXT, UNIQUE(channelid), UNIQUE(guildid), UNIQUE(webhookid));
CREATE TABLE IF NOT EXISTS mute (endsat BIGINT, guildid TEXT, userid TEXT, UNIQUE(guildid, userid));
CREATE TABLE IF NOT EXISTS muterole (guildid TEXT, roleid TEXT, UNIQUE(guildid), UNIQUE(roleid));
CREATE TABLE IF NOT EXISTS prefix (customprefix TEXT, guildid TEXT, UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS rules (guildid TEXT, rule TEXT, UNIQUE(guildid, rule));
CREATE TABLE IF NOT EXISTS scores (guildid TEXT, lvl INTEGER, points INTEGER, userid TEXT, UNIQUE(guildid, userid));
CREATE TABLE IF NOT EXISTS star (editid TEXT, msgid TEXT, UNIQUE(editid), UNIQUE(msgid));
CREATE TABLE IF NOT EXISTS starchannel (channelid TEXT, guildid TEXT, UNIQUE(channelid), UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS ticketcategory (channelid TEXT, guildid TEXT, UNIQUE(channelid), UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS togglelevel (bool BOOLEAN, guildid TEXT, UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS togglelog (bool BOOLEAN, guildid TEXT, UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS togglestar (bool BOOLEAN, guildid TEXT, UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS toggletickets (bool BOOLEAN, guildid TEXT, UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS togglewelcome (bool BOOLEAN, guildid TEXT, UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS updatechannel (channelid TEXT, guildid TEXT, UNIQUE(channelid), UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS usertag (tagcontent TEXT, tagname TEXT, userid TEXT, UNIQUE(tagname, userid));
CREATE TABLE IF NOT EXISTS warnings (guildid TEXT, userid TEXT, warnedat BIGINT, warnedby TEXT, warnreason TEXT, UNIQUE(guildid, userid, warnedat));
CREATE TABLE IF NOT EXISTS welcomechannel (channelid TEXT, guildid TEXT, UNIQUE(channelid), UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS welcomemsg (guildid TEXT, msg TEXT, UNIQUE(guildid));
CREATE TABLE IF NOT EXISTS work (endsat BIGINT, userid TEXT, UNIQUE(userid));
